data:
  train_data_path: null
  test_data_path: null
  prompts_per_rollout: null
  responses_per_prompt: null
  
actor:
  model_name: null
  use_liger_kernel: false
  gradient_checkpointing: true
  ddp_size: 1
  tp_size: 1
  sp_size: 1
  optimizer_dir: null
  max_length_per_device: null
  max_inference_length_per_device: ${actor.max_length_per_device}
  temperature: ${rollout.train_sampling_params.temperature}
  update_per_rollout: 1
  clip: 0.2
  lr: 1e-6
  weight_decay: 1e-2
  max_grad_norm: 1.0
  freeze_steps: 0
  offload_model: true
  offload_optimizer: true
  adv_estimator: ${adv.estimator}
  save_dir: ckpts/${trainer.experiment_name}/actor
  save_freq: null
  save_optimizer: true

  kl:
    coef: 0.0
    type: null # `reward` or `loss`
    reward_estimator: k1
    loss_estimator: k2
    # `k1`, `k2` or `k3`. See http://joschu.net/blog/kl-approx.html.

  entropy:
    coef: 1e-4

rollout:
  model_name: ${actor.model_name}
  tp_size: 1
  gpu_memory_utilization: 0.5
  responses_per_prompt: ${data.responses_per_prompt}
  train_sampling_params:
    temperature: 1.0
    max_new_tokens: null
  test_sampling_params:
    temperature: 0.0
    max_new_tokens: ${rollout.train_sampling_params.max_new_tokens}
  max_turns: 1
  env_path: null
  dynamic_filtering: true
  adv_estimator: ${adv.estimator}

ref_actor:
  model_name: ${actor.model_name}
  use_liger_kernel: ${actor.use_liger_kernel}
  ddp_size: ${actor.ddp_size}
  tp_size: ${actor.tp_size}
  sp_size: ${actor.sp_size}
  max_inference_length_per_device: ${actor.max_length_per_device}
  temperature: ${rollout.train_sampling_params.temperature}
  offload_model: ${actor.offload_model}

critic:
  model_name: ${actor.model_name}
  gradient_checkpointing: ${actor.gradient_checkpointing}
  ddp_size: ${actor.ddp_size}
  tp_size: ${actor.tp_size}
  sp_size: ${actor.sp_size}
  optimizer_dir: null
  max_length_per_device: ${actor.max_length_per_device}
  max_inference_length_per_device: ${critic.max_length_per_device}
  update_per_rollout: 12
  clip: 0.5
  lr: 5e-6
  weight_decay: ${actor.weight_decay}
  max_grad_norm: ${actor.max_grad_norm}
  offload_model: ${actor.offload_model}
  offload_optimizer: ${actor.offload_optimizer}
  save_dir: ckpts/${trainer.experiment_name}/critic
  save_freq: ${actor.save_freq}
  save_optimizer: ${actor.save_optimizer}

  lora:
    rank: 0
    alpha: 16
    target_modules: all-linear
    dropout: 0

adv:
  estimator: null # `reinforce` or `gae`
  gamma: 1.0
  lamda: 1.0
  norm_var: false
  
trainer:
  project: null
  experiment_name: null
  n_epochs: 1
  test_freq: null
  disable_wandb: false
  