data:
  path: null
  max_length: null
  batch_size: 128

actor:
  model_name: null
  use_liger_kernel: false
  optimizer_dir: null
  ddp_size: 1
  tp_size: 1
  sp_size: 1
  gradient_checkpointing: true
  max_length_per_device: null
  lr: 5e-6
  weight_decay: 1e-2
  max_grad_norm: 1.0
  warmup_ratio: 0.1
  offload_optimizer: true
  save_dir: ckpts/${trainer.experiment_name}
  save_freq: null
  save_optimizer: true

  lora:
    rank: 0
    alpha: 16
    target_modules: all-linear
    dropout: 0

trainer:
  project: null
  experiment_name: null
  n_epochs: 1
  disable_wandb: false